# Generated by Django 3.1 on 2020-08-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Employment',
                'verbose_name_plural': 'Employments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Сategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Сategory',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Location')),
                ('salary', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=70, null=True, verbose_name='Company')),
                ('url', models.CharField(blank=True, max_length=50, null=True, verbose_name='Url')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.сategory', verbose_name='Сategory')),
                ('employment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.employment_type', verbose_name='Employmet type')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.skill', verbose_name='Skill')),
                ('subcategores', models.ManyToManyField(to='main.Subcategory', verbose_name='Subcategory')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-published'],
            },
        ),
    ]
