# Generated by Django 3.1 on 2020-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='img',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Vacancy_img'),
        ),
    ]
