# Generated by Django 3.1 on 2020-08-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vacancie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancie',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='requirements'),
        ),
    ]
