# Generated by Django 3.1 on 2020-08-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200826_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(null=True, upload_to='img/subcategory', verbose_name='Subcategory_img'),
        ),
    ]
