# Generated by Django 3.1 on 2020-08-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subcategory_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img/subcategory', verbose_name='Subcategory_img'),
        ),
        migrations.AlterField(
            model_name='vacancie',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Vacancy_img'),
        ),
    ]
